### ISSUE TITLE
problem when run metgrid.exe

### ISSUE THREAD

**Issue by Nawahda-Amin** [anikfal/atmospheric_science#2]
Dear Dr. Amirhussein
I have a question regarding ungrib of ERA5 data; when downloading both surface and level data is it necessary to set the domain to be exactly the same as the domain in the geogrid part of the namelist.wps, Ive selected a domain which is a little larger but I got the following errors when run ./metgrid.exe, do you think it is the cause of this error or could be another issue?

Processing domain 1 of 2
 Processing 2015-03-01_00
    SFC
    PL
WARNING: Field PRES has missing values at level 200100 at (i,j)=(1,1)
WARNING: Field GHT has missing values at level 200100 at (i,j)=(1,1)
WARNING: Field PMSL has missing values at level 200100 at (i,j)=(1,1)
WARNING: Field PSFC has missing values at level 200100 at (i,j)=(1,1)
WARNING: Field SOILHGT has missing values at level 200100 at (i,j)=(1,1)
ERROR: Missing values encountered in interpolated fields. Stopping.
Note: The following floating-point exceptions are signalling: IEEE_OVERFLOW_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

**Comment by anikfal** [comment]
Hi Amin,

Before downloading EAR5 (or FNL, etc.), investigate the lat/lon of your WRF domain and be sure that the ERA5 domain can entirely cover your WRF domain. Otherwise, you will get the error you showed in this issue.

You can [plot your WRF domain by PostWRF](https://postwrf.readthedocs.io/en/latest/domain.html), to find out the exact extent of your WRF domain.
